language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "2.7"
dist: trusty

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility

stages:
  - test

jobs:
  include:
    # Test all other addons together
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT=1
          EXCLUDE="account_asset_management_capital_improvement_operating_unit,account_asset_management_complex_asset_operating_unit,account_asset_management_estimation_change_operating_unit,account_asset_management_impairment_operating_unit,account_asset_management_operating_unit,account_asset_management_retirement_by_donation_operating_unit,account_asset_management_retirement_by_missing_operating_unit,account_asset_management_retirement_by_scrap_operating_unit,account_asset_management_retirement_by_stolen_operating_unit,account_asset_management_retirement_sale_operating_unit,account_asset_management_stock_operating_unit"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB"
          EXCLUDE="account_asset_management_capital_improvement_operating_unit,account_asset_management_complex_asset_operating_unit,account_asset_management_estimation_change_operating_unit,account_asset_management_impairment_operating_unit,account_asset_management_operating_unit,account_asset_management_retirement_by_donation_operating_unit,account_asset_management_retirement_by_missing_operating_unit,account_asset_management_retirement_by_scrap_operating_unit,account_asset_management_retirement_by_stolen_operating_unit,account_asset_management_retirement_sale_operating_unit,account_asset_management_stock_operating_unit"
env:
  global:
    - VERSION="8.0" TESTS="0" LINT_CHECK="0" MAKEPOT="1"

install:
  - git clone --depth=1
    https://github.com/simetri-sinergi-id/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
